---
- name: nextcloud for raspbian
  hosts: localhost
  connection: local
  gather_facts: true
  become: true
  become_user: root
  tasks:

    - name: add docker apt key
      apt_key:
        url: https://download.docker.com/linux/raspbian/gpg
        state: present

    - name: add docker apt repo
      apt_repository:
        repo: deb [arch=armhf] https://download.docker.com/linux/raspbian buster stable
        state: present

    - name: required packages
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - docker-ce
          - libcap2-bin
          - python3-pip
          - raspberrypi-kernel-headers
          - ssl-cert
        state: latest
        update_cache: yes

    - name: ansible docker system python
      pip:
        name:
          - ansible
          - docker
        executable: /usr/bin/pip3
        state: latest

    - name: docker service started/enabled
      systemd:
        name: docker
        state: started
        enabled: True

    - name: db user
      user:
        name: nextclouddb
        shell: /bin/bash
        create_home: False
      register: db_user

    - name: set ip fact for webproxy
      set_fact:
        instance_public_ip: "{{ ansible_default_ipv4.address }}"

    - name: web_port if not defined
      set_fact:
        web_port: "{% if web_port is not defined %}443{% else %}{{ web_port }}{% endif %}"

    - name: oo_port if not defined
      set_fact:
        oo_port: "{% if oo_port is not defined %}8443{% else %}{{ oo_port }}{% endif %}"

    - name: project_directory if not defined
      set_fact:
        project_directory: "{% if project_directory is not defined %}/opt{% else %}{{ project_directory }}{% endif %}"

    - name: various container directories - application
      file:
        path: "{{ item }}"
        state: directory
        owner: www-data
        mode: '0750'
      with_items:
        - "{{ project_directory }}/nextcloud_application"
        - "{{ project_directory }}/nextcloud_application/var"
        - "{{ project_directory }}/nextcloud_application/var/www"
        - "{{ project_directory }}/nextcloud_application/var/www/html"
        - "{{ project_directory }}/nextcloud_application/var/www/html/custom_apps"
        - "{{ project_directory }}/nextcloud_application/var/www/html/config"
        - "{{ project_directory }}/nextcloud_application/var/www/html/data"

    - name: various container directories - webproxy
      file:
        path: "{{ item }}"
        state: directory
        owner: root
        group: root
        mode: '0750'
      with_items:
        - "{{ project_directory }}/nextcloud_webproxy"

    - name: various container directories - db
      file:
        path: "{{ item }}"
        state: directory
        owner: "{{ db_user.name }}"
        group: "{{ db_user.group }}"
        mode: '0750'
      with_items:
        - "{{ project_directory }}/nextcloud_database"

    - name: secure web proxy
      template:
        src: "{{ item }}"
        dest: "{{ project_directory }}/nextcloud_webproxy/{{ item }}"
        owner: root
        group: root
        mode: 0444
      with_items:
        - httpd-ssl.conf
        - httpd.conf

    - name: Determine admin_password file exists
      stat:
        path: "{{ project_directory }}/nextcloud_application/admin_password"
      register: admin_password_file

    - name: Generate admin_password if not exists
      set_fact:
        admin_password: "{{ lookup('password', '/dev/null length=15 chars=ascii_letters') }}"
      when: admin_password_file.stat.exists|bool == False
      no_log: True

    - name: Set admin_password if not exists
      lineinfile:
        path: "{{ project_directory }}/nextcloud_application/admin_password"
        create: yes
        owner: root
        group: root
        mode: '0600'
        line: "{{ admin_password }}"
      when: admin_password_file.stat.exists|bool == False

    - name: Determine db_password file exists
      stat:
        path: "{{ project_directory }}/nextcloud_application/db_password"
      register: db_password_file

    - name: Generate db_password if not exists
      set_fact:
        db_password: "{{ lookup('password', '/dev/null length=15 chars=ascii_letters') }}"
      when: db_password_file.stat.exists|bool == False
      no_log: True

    - name: Set db_password if not exists
      lineinfile:
        path: "{{ project_directory }}/nextcloud_application/db_password"
        create: yes
        owner: root
        group: root
        mode: '0600'
        line: "{{ db_password }}"
      when: db_password_file.stat.exists|bool == False

    - name: Determine oo_password file exists
      stat:
        path: "{{ project_directory }}/nextcloud_application/oo_password"
      register: oo_password_file

    - name: Generate oo_password if not exists
      set_fact:
        oo_password: "{{ lookup('password', '/dev/null length=15 chars=ascii_letters') }}"
      when: oo_password_file.stat.exists|bool == False
      no_log: True

    - name: Set oo_password if not exists
      lineinfile:
        path: "{{ project_directory }}/nextcloud_application/oo_password"
        create: yes
        owner: root
        group: root
        mode: '0600'
        line: "{{ oo_password }}"
      when: oo_password_file.stat.exists|bool == False

    - name: Get admin_password if exists
      slurp:
        src: "{{ project_directory }}/nextcloud_application/admin_password"
      register: admin_password_content
      when: admin_password_file.stat.exists|bool == True

    - name: Get db_password if exists
      slurp:
        src: "{{ project_directory }}/nextcloud_application/db_password"
      register: db_password_content
      when: db_password_file.stat.exists|bool == True

    - name: Get oo_password if exists
      slurp:
        src: "{{ project_directory }}/nextcloud_application/oo_password"
      register: oo_password_content
      when: oo_password_file.stat.exists|bool == True

    - name: Register admin_password if exists
      set_fact:
        admin_password: "{{ admin_password_content['content'] | b64decode | trim }}"
      when: admin_password_file.stat.exists|bool == True

    - name: Register db_password if exists
      set_fact:
        db_password: "{{ db_password_content['content'] | b64decode | trim }}"
      when: db_password_file.stat.exists|bool == True

    - name: Register oo_password if exists
      set_fact:
        oo_password: "{{ oo_password_content['content'] | b64decode | trim }}"
      when: oo_password_file.stat.exists|bool == True

    - name: docker network
      docker_network:
        name: cloudoffice
        driver: bridge
        ipam_config:
          - subnet: "{{ docker_network }}/24"
            gateway: "{{ docker_gw }}"

    - name: db container
      docker_container:
        name: cloudoffice_database
        hostname: cloudofficedatabase
        image: linuxserver/mariadb:latest
        networks:
          - name: cloudoffice
            ipv4_address: "{{ docker_db }}"
        env:
          MYSQL_ROOT_PASSWORD: "{{ admin_password }}"
          MYSQL_PASSWORD: "{{ db_password }}"
          MYSQL_DATABASE: nextcloud
          MYSQL_USER: nextcloud
          PUID: "{{ db_user.uid }}"
          PGID: "{{ db_user.group }}"
        volumes:
          - "{{ project_directory }}/nextcloud_database:/config:rw"
        pull: yes
        purge_networks: yes
        restart_policy: "always"
        container_default_behavior: "compatibility"

    - name: nextcloud container
      docker_container:
        name: cloudoffice_nextcloud
        hostname: cloudofficenextcloud
        image: nextcloud:latest
        networks:
          - name: cloudoffice
            ipv4_address: "{{ docker_nextcloud }}"
        env:
          NEXTCLOUD_ADMIN_PASSWORD: "{{ admin_password }}"
          NEXTCLOUD_ADMIN_USER: ncadmin
          NEXTCLOUD_TRUSTED_DOMAINS: "{{ instance_public_ip }} {{ docker_webproxy }} {{ docker_nextcloud }}"
          TRUSTED_PROXIES: "{{ instance_public_ip }} {{ docker_webproxy }}"
          OVERWRITEHOST: "{{ instance_public_ip }}:{{ web_port }}"
          OVERWRITEPROTOCOL: https
          MYSQL_PASSWORD: "{{ db_password }}"
          MYSQL_DATABASE: nextcloud
          MYSQL_USER: nextcloud
          MYSQL_HOST: "{{ docker_db }}"
        volumes:
          - "{{ project_directory }}/nextcloud_application/var/www/html:/var/www/html:rw"
          - "{{ project_directory }}/nextcloud_application/var/www/html/custom_apps:/var/www/html/custom_apps:rw"
          - "{{ project_directory }}/nextcloud_application/var/www/html/config:/var/www/html/config:rw"
          - "{{ project_directory }}/nextcloud_application/var/www/html/data:/var/www/html/data:rw"
          - "{{ project_directory }}/nextcloud_application/var/www/html/themes:/var/www/html/themes:rw"
        pull: yes
        purge_networks: yes
        restart_policy: "always"
        container_default_behavior: "compatibility"

    - name: web proxy container
      docker_container:
        name: cloudoffice_webproxy
        hostname: cloudofficewebproxy
        image: httpd:2.4
        networks:
          - name: cloudoffice
            ipv4_address: "{{ docker_webproxy }}"
        ports:
          - "{{ web_port }}:{{ web_port }}"
        volumes:
          - "{{ project_directory }}/nextcloud_webproxy/httpd-ssl.conf:/usr/local/apache2/conf/extra/httpd-ssl.conf:ro"
          - "{{ project_directory }}/nextcloud_webproxy/httpd.conf:/usr/local/apache2/conf/httpd.conf:ro"
          - /etc/ssl/certs/ssl-cert-snakeoil.pem:/usr/local/apache2/conf/server.crt:ro
          - /etc/ssl/private/ssl-cert-snakeoil.key:/usr/local/apache2/conf/server.key:ro
        pull: yes
        purge_networks: yes
        restart_policy: "always"
        container_default_behavior: "compatibility"

    - name: onlyoffice container
      docker_container:
        name: cloudoffice_onlyoffice
        hostname: cloudofficeonlyoffice
        image: onlyoffice/documentserver
        networks:
          - name: cloudoffice
            ipv4_address: "{{ docker_onlyoffice }}"
        env:
          ONLYOFFICE_HTTPS_HSTS_ENABLED: "false"
          USE_UNAUTHORIZED_STORAGE: "true"
          JWT_ENABLED: "true"
          JWT_SECRET: "{{ oo_password }}"
        volumes:
          - /opt/nextcloud_onlyoffice:/var/www/onlyoffice/Data:rw
          - /etc/ssl/certs/ssl-cert-snakeoil.pem:/var/www/onlyoffice/Data/certs/onlyoffice.crt:ro
          - /etc/ssl/private/ssl-cert-snakeoil.key:/var/www/onlyoffice/Data/certs/onlyoffice.key:ro
        ports:
          - "{{ oo_port }}:443"
        pull: yes
        purge_networks: yes
        restart_policy: "always"
        container_default_behavior: "no_defaults"
        auto_remove: no
        detach: yes
        init: no
        interactive: no
        memory: "0"
        paused: no
        read_only: no
        tty: yes
      no_log: True

    - name: nextcloud onlyoffice and talk scripts (clear)
      file:
        path: "{{ project_directory }}/nextcloud_application/nextcloud-{{ item }}.sh"
        state: absent
      with_items:
        - onlyoffice
        - talk

    - name: nextcloud onlyoffice (set)
      lineinfile:
        path: "{{ project_directory }}/nextcloud_application/nextcloud-onlyoffice.sh"
        create: yes
        owner: root
        group: root
        mode: '0500'
        line: "{{ item }}"
      no_log: True
      with_items:
        - "#!/bin/bash"
        - "# install and configure onlyoffice connector"
        - "docker exec --user www-data cloudoffice_nextcloud php occ app:install onlyoffice"
        - "docker exec --user www-data cloudoffice_nextcloud php occ app:enable onlyoffice"
        - "docker exec --user www-data cloudoffice_nextcloud php occ config:system:set onlyoffice DocumentServerUrl --value='https://{{ instance_public_ip }}:{{ oo_port }}/'"
        - "docker exec --user www-data cloudoffice_nextcloud php occ config:system:set onlyoffice verify_peer_off --value=true --type=boolean"
        - "docker exec --user www-data cloudoffice_nextcloud php occ config:app:set onlyoffice disable_certificate_verification --value='yes'"
        - "docker exec --user www-data cloudoffice_nextcloud php occ config:app:set onlyoffice jwt_secret --value {{ oo_password }}"

    - name: nextcloud talk (set)
      lineinfile:
        path: "{{ project_directory }}/nextcloud_application/nextcloud-talk.sh"
        create: yes
        owner: root
        group: root
        mode: '0500'
        line: "{{ item }}"
      with_items:
        - "#!/bin/bash"
        - "# install spreed (talk)"
        - "docker exec --user www-data cloudoffice_nextcloud php occ app:install spreed"
        - "docker exec --user www-data cloudoffice_nextcloud php occ app:enable spreed"

    - name: wait for nextcloud 200OK
      uri:
        url: "https://127.0.0.1:{{ web_port }}/login"
        status_code: 200
        validate_certs: no
      register: nc_wait_result
      until: nc_wait_result.status == 200
      retries: 180
      delay: 1

    - name: nextcloud onlyoffice and talk (execute)
      shell:
        cmd: "{{ project_directory }}/nextcloud_application/nextcloud-{{ item }}.sh"
      args:
        executable: /bin/bash
      no_log: True
      with_items:
        - onlyoffice
        - talk

    - name: Playbook Summary
      debug:
        msg:
          - "CloudOffice completed installation!"
          - "Nextcloud WebUI: https://{{ ansible_default_ipv4.address }}:{{ web_port }}"
